config/routes.rb
WebBreaker::Engine.routes.draw do
  root to: 'external_services#index'

  resources :external_services do
    put :toggle, on: :member
  end

end

app/models/web_breaker/external_service.rb
module WebBreaker
  class ExternalService < ActiveRecord::Base

    attr_accessible :enabled, :host, :name

    validates_presence_of :name
    validates_presence_of :host

    def toggle_enabled
      if enabled?
        disable
      else
        enable
      end
    end

    def enable
      update_attribute(:enabled, true)
    end

    def disable
      update_attribute(:enabled, false)
    end

  end
end

app/models/web_breaker/web_proxy.rb
module WebBreaker


  module WebProxy

    def self.filter_request(host, path)
      return yield unless WebBreaker.configuration.enabled?

      service = ExternalService.find_by_host(host)

      if !service || service.enabled?
        yield
      else
        raise WebBreaker::ServiceDisabledError
      end
    end

  end
end

app/controllers/web_breaker/application_controller.rb
module WebBreaker
  class ApplicationController < ActionController::Base

    before_filter :ensure_web_breaker_enabled

    private

      def ensure_web_breaker_enabled
        raise ActionController::RoutingError.new('Not Found') unless WebBreaker.configuration.enabled?
      end

  end
end

app/controllers/web_breaker/external_services_controller.rb
require_dependency "web_breaker/application_controller"

module WebBreaker
  class ExternalServicesController < ApplicationController

    before_filter :find_service, only: [:edit, :update, :destroy, :toggle]

    def index
      @services = ExternalService.all
    end

    def new
      @service = ExternalService.new
    end

    def edit
    end

    def create
      @service = ExternalService.new(params[:external_service])

      if @service.save
        redirect_to external_services_path, notice: 'External Service was successfully created.'
      else
        render action: 'new'
      end
    end

    def update
      if @service.update_attributes(params[:external_service])
        redirect_to external_services_path, notice: 'External Service was successfully updated.'
      else
        render action: 'edit'
      end
    end

    def toggle
      @service.toggle_enabled
      head :ok
    end

    def destroy
      @service.destroy

      redirect_to external_services_path, notice: 'External Service was successfully deleted.'
    end

    private

      def find_service
        @service = ExternalService.find(params[:id])
      end

  end
end

app/helpers/web_breaker/application_helper.rb
module WebBreaker
  module ApplicationHelper

    def icon_tag(name, options = {})
      klass = "icon-#{name.to_s}"
      klass << " icon-white" unless options[:black]
      content_tag :i, '', class: klass
    end

    def badge_tag(content, state = nil)
      html_class = 'label'
      html_class << " label-#{state}" if state

      content_tag :span, content, class: html_class
    end

    def link_to_with_icon(icon, body, options = {}, html_options = {})
      link_to(options, html_options) do
        "#{icon_tag(icon)} #{body}".html_safe
      end
    end

  end
end

app/helpers/web_breaker/external_services_helper.rb
module WebBreaker
  module ExternalServicesHelper
  end
end

app/views/layouts/web_breaker/application.html.haml
!!! Strict
%html{:lang => "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=IE7"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %title WebBreaker
    = csrf_meta_tags
    /[if lt IE 9]
      %script(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")

    = stylesheet_link_tag "web_breaker/application", :media => "all"

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to 'WebBreaker', root_path, :class => 'brand'

    .container
      = render 'messages'
      = yield

    = javascript_include_tag 'web_breaker/application'

app/views/web_breaker/application/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/web_breaker/external_services/_form.html.haml
= simple_form_for @service do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :host

  .form-actions
    = link_to 'Cancel', external_services_path, class: 'btn'
    = f.button :submit, class: 'btn btn-primary'

app/views/web_breaker/external_services/edit.html.haml
%h1 Edit External Service
%br

= render 'form'

app/views/web_breaker/external_services/index.html.haml
- if @services.empty?

  .hero-unit
    %h1 Create your first External Service!
    %p Ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
    %p
      = link_to_with_icon 'plus', 'New External Service', new_external_service_path, class: 'btn btn-primary'

- else

  %table.table.table-striped

    %tbody
      %thead
        %tr
          %th Name
          %th Host
          %th

      - @services.each do |service|
        %tr

          %td= service.name

          %td= service.host

          %td

            %div.pull-right.switch.switch-small.service-toggle{ style: 'margin-left: 20px;'}
              = check_box_tag 'enabled', true, service.enabled?, data: { id: service.id }

            .btn-group.pull-right{style: 'margin-top: 2px;'}
              = link_to [:edit, service], class: 'btn btn-mini' do
                = icon_tag 'pencil', black: true
              = link_to service, class: 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this external service?' } do
                = icon_tag 'trash'

  %p
    = link_to_with_icon 'plus', 'New External Service', new_external_service_path, class: 'btn btn-primary'

app/views/web_breaker/external_services/new.html.haml
%h1 New External Service
%br

= render 'form'